# Generated by Django 3.1.6 on 2021-02-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20210206_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='passowrd',
            new_name='password',
        ),
    ]
